services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development

    env_file:
      - ./server/.env

    ports:
      - "8000:8000"

    volumes:
      - ./server/app:/app/app
      - ./server/tests:/app/tests