"""add jobs idempotency key

Revision ID: 478a7a3c6ff3
Revises: 1dd99accaefd
Create Date: 2026-09-22 22:31:00.896481

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '478a7a3c6ff3'
down_revision: str | Sequence[str] | None = '1dd99accaefd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('idempotency_key', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'jobs', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'jobs', type_='unique')
    op.drop_column('jobs', 'idempotency_key')
    # ### end Alembic commands ###
